//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCampaignB2b.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable, DataContract(IsReference = true)]
    public partial class AGENT_CAMP_CRITERIA_MASTER
    {
        [DataMember] public int ID { get; set; }
        [DataMember] public string CriteriaName { get; set; }
        [DataMember] public Nullable<bool> ActiveSw { get; set; }
    }
}
