//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCampaignB2b.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable, DataContract(IsReference = true)]
    public partial class AGENT_CAMP_CRITERIA
    {
        [DataMember] public int AGENT_CAMP_ID { get; set; }
        [DataMember] public int PRIORITY { get; set; }
        [DataMember] public int PERCENT_APPLIED { get; set; }
        [DataMember] public string QUERY { get; set; }
        [DataMember] public string DESCRIPTION { get; set; }
        [DataMember] public int AGENT_CAMP_CRITERIA_ID { get; set; }
        [DataMember] public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        [DataMember] public Nullable<int> LAST_UPDATED_BY { get; set; }
        [DataMember] public byte[] LAST_TIMESTAMP { get; set; }
    
        [DataMember] public virtual AGENT_CAMP AGENT_CAMP { get; set; }
    }
}
