//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCampaignB2b.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable, DataContract(IsReference = true)]
    public partial class LIST_META_DATA
    {
        [DataMember] public int LIST_META_DATA_ID { get; set; }
        [DataMember] public string LIST_NAME { get; set; }
        [DataMember] public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        [DataMember] public string QUARTER { get; set; }
        [DataMember] public string LIST_ID { get; set; }
        [DataMember] public Nullable<bool> IsOnDispReport { get; set; }
        [DataMember] public string ActiveOrInactive { get; set; }
        [DataMember] public byte[] LAST_TIMESTAMP { get; set; }
        [DataMember] public Nullable<int> records_received { get; set; }
        [DataMember] public string LIST_TYPE { get; set; }
        [DataMember] public string LIST_SEGMENT { get; set; }
    }
}
