//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCampaignB2b.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pd_cmcEntities : DbContext
    {
        public pd_cmcEntities()
            : base("name=pd_cmcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENT_CAMP> AGENT_CAMP { get; set; }
        public DbSet<AGENT_CAMP_CRITERIA> AGENT_CAMP_CRITERIA { get; set; }
        public DbSet<AGENT_CAMP_CRITERIA_MASTER> AGENT_CAMP_CRITERIA_MASTER { get; set; }
        public DbSet<LIST_META_DATA> LIST_META_DATA { get; set; }
    }
}
